num_replicas: 4

replica_0:
  sk_seed: 1
  hostname: "172.31.40.133"

replica_1:
  sk_seed: 2
  hostname: "172.31.36.17"

replica_2:
  sk_seed: 3
  hostname: "172.31.43.31"

replica_3:
  sk_seed: 4
  hostname: "172.31.37.247"
