num_replicas: 4

replica_0:
  sk_seed: 1
  hostname: "172.31.43.11"

replica_1:
  sk_seed: 2
  hostname: "172.31.32.43"

replica_2:
  sk_seed: 3
  hostname: "172.31.40.3"

replica_3:
  sk_seed: 4
  hostname: "172.31.39.71"
