---
- name: autogen configure
  hosts: all
  tasks:
          - name: autogen configure
            shell: "cd ~/xfs/speedex && ./autogen.sh && ./configure DEFINES=\"-D_LOG_TRANSFERS -D_LOG_HASH_RECORDS\""

