---
- name: autogen configure
  hosts: all
  tasks:
          - name: autogen configure
            shell: "cd ~/xfs/speedex && ./autogen.sh && ./configure DEFINES=\"-D_MAX_SEQ_NUMS_PER_BLOCK=50000 -D_DISABLE_TATONNEMENT_TIMEOUT -D_DISABLE_PRICE_COMPUTATION\""

