- name: set config aws
  hosts: all
  tasks:
    - name: upload config
      ansible.builtin.copy:
        src: ../config/config_aws_generated.yaml
        dest: ~/xfs/speedex/config/config_aws_generated.yaml
        mode: '0666'
    - name: set config
      shell: "cd ~/xfs/speedex/automation && echo \"config/config_aws_generated.yaml\" > config_file"
