num_replicas: 4

replica_0:
  sk_seed: 1
  hostname: "10.0.0.1"

replica_1:
  sk_seed: 2
  hostname: "10.0.0.2"

replica_2:
  sk_seed: 3
  hostname: "10.0.0.3"

replica_3:
  sk_seed: 4
  hostname: "10.0.0.4"
